version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: someKey
      MINIO_SECRET_KEY: someSecret
    volumes:
      - ./data/:/data/
    command: server /data
